### PR TITLE
Fix #1211 - SVG: support namespace prefix

### LINKED ISSUE #1211: SVG using a namespace are not recognized
**Describe the bug**
This SVG syntax with a namespace is not recognized by SVGImageReaderSpi.canDecode:

```svg
<?xml version='1.0' encoding='utf-8'?>
<ns0:svg xmlns:ns0="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 500 500">
```

because the method expects [no namespace](https://github.com/haraldk/TwelveMonkeys/blob/twelvemonkeys-3.12.0/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java#L134) (i.e. plain "svg" tag):

```java
                    // This is a normal tag
                    if (buffer[0] == 's' && buffer[1] == 'v' && buffer[2] == 'g'
                            && (Character.isWhitespace((char) buffer[3]) || buffer[3] == ':')) {
                        // It's SVG, identified by root tag
                        // TODO: Support svg with prefix + recognize namespace (http://www.w3.org/2000/svg)!
                        return true;
                    }

                    // If the tag is not "svg", this isn't SVG
                    return false;
```

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.12.0

2. The *exact* output of `java --version`. 

    openjdk version "25" 2025-09-16 LTS
    OpenJDK Runtime Environment Temurin-25+36 (build 25+36-LTS)
    OpenJDK 64-Bit Server VM Temurin-25+36 (build 25+36-LTS, mixed mode, sharing)

3. N/A

**To Reproduce**

1. Compile the below sample code
2. Download the sample image file
3. Run the code with the sample file

**Expected behavior**
These files are valid SVG and should be recognized as such.

**Example code**
```java
import org.junit.jupiter.api.Test;

import javax.imageio.stream.ImageInputStream;
import javax.imageio.ImageIO;
import java.io.InputStream;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.*;

class SVGImageReaderSpiTest {

    @Test
    void testCanDecodeSVGwithNamespace() throws Exception {
        try (InputStream input = new URL("https://bioart.niaid.nih.gov/api/bioarts/500/files/636154").openStream();
             ImageInputStream imageInputStream = ImageIO.createImageInputStream(input)) {
            assertTrue(new SVGImageReaderSpi().canDecodeInput(imageInputStream));
        }
    }
}
```

**Sample file(s)**
Attach any sample files needed to reproduce the problem. Use a ZIP-file if the format is not directly supported by GitHub.

**Stak trace**
N/A

**Screenshots**
N/A

**Additional context**
These files are public domain from U.S. NIH BioArt: https://bioart.niaid.nih.gov/bioart/500

Image

### PR DESCRIPTION
**Pull request by don-vip**

### CODE REVIEW

File: imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java [hunk 1]
```diff
@@ -134,10 +136,40 @@ else if (buffer[1] == 'D' && buffer[2] == 'O' && buffer[3] == 'C'
                     if (buffer[0] == 's' && buffer[1] == 'v' && buffer[2] == 'g'
                             && (Character.isWhitespace((char) buffer[3]) || buffer[3] == ':')) {
                         // It's SVG, identified by root tag
-                        // TODO: Support svg with prefix + recognize namespace (http://www.w3.org/2000/svg)!
                         return true;
                     }
 
+                    // Read the full tag name (may contain a prefix of any length)
+                    ByteArrayOutputStream nameBuf = new ByteArrayOutputStream();
```
Comment (haraldk) [inline imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java]: As the default buffer size is 32, we can optimize this by allocating enough space up front. 

```suggestion
                    int MAX_TAG_NAME = 256;
                    ByteArrayOutputStream nameBuf = new ByteArrayOutputStream(MAX_TAG_NAME);
```

Or possibly use 1024, and reuse the buffer for the attribute search?

File: imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java [hunk 2]
```diff
@@ -157,6 +189,21 @@ else if (buffer[1] == 'D' && buffer[2] == 'O' && buffer[3] == 'C'
...
     }
 
+    private static void readBuffer(final ImageInputStream input, final ByteArrayOutputStream buffer,
+            final Predicate<ByteArrayOutputStream> loopCondition, Predicate<Byte> breakCondition) throws IOException {
+        while (loopCondition.test(buffer)) {
+            int r = input.read();
+            if (r == -1) {
+                throw new EOFException();
+            }
+            byte bb = (byte) r;
```
[the remark this answers is not in the document]
Comment (don-vip) [reply imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java]: done!

File: imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java (hunk 1 above)
Comment (don-vip) [reply imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java]: done :)

File: imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java [hunk 3]
```diff
@@ -134,10 +136,40 @@ else if (buffer[1] == 'D' && buffer[2] == 'O' && buffer[3] == 'C'
...
+                        bb -> bb == '>' || Character.isWhitespace(bb) || bb == '/');
+
+                    if (nameBuf.toString("US-ASCII").toLowerCase(Locale.ENGLISH).endsWith(":svg")) {
+                        // Scan the rest of the tag attributes until '>' to find the SVG namespace URI
+                        ByteArrayOutputStream attrBuf = new ByteArrayOutputStream();
+                        final int MAX_ATTR_SCAN = 1024; // safe upper bound to keep it fast
+                        readBuffer(input, attrBuf, x -> x.size() < MAX_ATTR_SCAN, bb -> bb == '>');
+
+                        // If the tag contains the SVG namespace, it's SVG.
+                        if (attrBuf.toString("US-ASCII").contains("http://www.w3.org/2000/svg")) {
```
[the remark this answers is not in the document]
Comment (don-vip) [reply imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java]: Good idea, I changed it to a regex and added a few invalid cases in the unit test, it's more reliable now.

File: imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java (hunk 1 above)
Comment (don-vip) [reply imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReaderSpi.java]: woops

**Comment by don-vip** [comment]
@haraldk I think everything has been taken into account :)

**Review by haraldk — APPROVED** [review]
